apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}.registry
  labels:
    env: {{ .Value.app.env }}
    name: {{ .Value.app.name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    version: {{ .Chart.AppVersion }}
type: kubernetes.io/dockerconfigjson

---
{{- if .Value.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}.postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    env: {{ .Value.app.env }}
    name: {{ .Value.app.name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    version: {{ .Chart.AppVersion }}
data:
  host: {{ .Value.postgresql.host | b64enc }}
  port: {{ .Value.postgresql.port | toString | b64enc }}
  database: {{ .Value.postgresql.database | b64enc }}
  username: {{ .Value.postgresql.uname | b64enc }}
  password: {{ .Value.postgresql.pword | b64enc }}


{{- end }}