apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    env: {{ .Value.app.env }}
    name: {{ .Value.app.name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    version: {{ .Chart.AppVersion }}

spec:
  type: {{ .Value.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Value.service.port }}
      targetPort: {{ .Value.container.port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}