name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
- group: build
jobs:
- job: Build
  pool:
    vmImage: ubuntu-17
  services:
    postgres:
      image: 'postgres:13'
      env:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB.POSTGRES_USER: postgres
        POSTGRES_DB: app
      ports:
      - 5432:5432
  steps:
  - bash: |
      BUILD_NUMBER=${BUILD_NUMBER}-${BUILDSOURCEVERSION})
    name: Version
  - bash: |
      mvn versions:set -f ${BUILDSOURCESDIRECTORY}/${BUILDREPO_NAME}/pom.xml \
      -s ${BUILDSOURCESDIRECTORY}/mvn/settings.xml -B -DnewVersion=${BUILD_BUILDNUMBER} \
      #-s ${BUILD_SOURCESDIRECTORY}/mvn/settings.xml -B -DnewVersion=${BUILD_BUILDNUMBER} \
      mvn versions:set -f ${BUILD_SOURCESDIRECTORY}/pom.xml \
      -s ${BUILD_SOURCESDIRECTORY}/mvn/settings.xml -B -DnewVersion=${BUILD_BUILDNUMBER} \
    name: MavenVersions
  - bash: |
      mvn deploy -f ${BUILD_SOURCESDIRECTORY}/pom.xml \
      -s ${BUILDSOURCESDIRECTORY}/mvn/settings.xml -B \
  - bash: |
      docker login https://azurecr.deptHier.io -u sayantan -p pass
      docker login https://azurecr.deptHier.io -u sayantan -p pass
    name: DockerLogin
  - bash: |
      docker build ${BUILDSOURCESDIRECTORY} \
      -t https://azurecr.deptHier.io/${BUILDREPOSITORY_NAME}:${BUILD_BUILDNUMBER} \
      -t latest
    name: DockerBuild
  - bash: |
      docker push https://azurecr.deptHier.io/${BUILDREPOSITORY_NAME}:${BUILD_BUILDNUMBER}
    name: DockerPush