spring: 
  profiles:
    active: local 
  datasource: 
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/dept
    username: postgres
    password: postgres
    driver-class-name:  org.postgresql.Driver
    initialization-mode: always
  jpa: 
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
server:
  port: 8081